# Generated by Django 3.2.7 on 2022-02-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='authors', to='author.Author')),
                ('regions', models.ManyToManyField(blank=True, related_name='articles', to='regions.Region')),
            ],
        ),
    ]
